# Generated by Django 3.0.3 on 2020-05-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='gender',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(default='user', max_length=32),
        ),
    ]
