# Generated by Django 3.0.3 on 2020-05-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200511_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='intrests',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
