# Generated by Django 3.0.3 on 2020-05-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20200511_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categor',
            new_name='category',
        ),
    ]
